### ISSUE TITLE
A newbie on Python who really wants to use your program

### ISSUE THREAD

**Issue by Karth53** [karas84/ProjectZeroUndub#1]
As a total newbie about python, can you help me patching the files? Python 3.7 or newer kept crashing when launched, so I tried to use Thonny (which have a simpler interface), downloaded the required modules but I don't know where to write the paths of the iso files.
Also, do you think it would work on the Free DVD boot hack ?
<img width="960" alt="thonny pbm" src="https://user-images.githubusercontent.com/118351122/203750433-7b324f8b-5a0f-438a-90ab-c81074ce41ae.png">

**Comment by karas84** [comment]
Hi @Karth53 , as you can see in the error message, the problem is that you are not passing the necessary arguments to the program. You need to at least specify (in this order) the path of the European ISO, the path of the Japanese ISO, and the output path of the undubbed ISO. Then, optionally, you can pass some extra arguments (refer to the readme for more info).

I have to admit I never used Thonny, but it seems that to pass the arguments you need to enable them from `View > Program arguments`, and put them in the text field on the top right.

As for the DVD boot hack, I suppose it should work but I never tried it. If patching the iso fails, you can always patch it for ESR and then use freedvdboot to boot the ESR elf to run it.

Let me know if you manage to do it.

**Comment by Karth53** [comment]
Thank you for your help. The issue I'm now facing is the following:
"Error while accessing ISO files.
Some input ISO files cannot be accessed or read.
Please check that the provided files exist and that they can be read."

when entering those arguments: "C:\Users\soson\Desktop\Project Zero (Europe).iso", "C:\Users\soson\Desktop\Zero (Japan).iso", "C:\Users\soson\Desktop\Project Zero (Europe Undubbed).iso"

Changing the isos involved by others haven't changed the outcome. Any idea why ?

**Comment by karas84** [comment]
Try using double quotes around paths and don't use commas to separate arguments, just spaces:

`"C:\Users\soson\Desktop\Project Zero (Europe).iso" "C:\Users\soson\Desktop\Zero (Japan).iso" "C:\Users\soson\Desktop\Project Zero (Europe Undubbed).iso"`

Just tried it on Thonny on my windows system and it worked.

**Comment by Karth53** [comment]
You were right ! It now works like a charm whether on emulator or on real hardware with free DVD boot.
Once again, thank you for your help and good luck with your future projects!

**Comment by karas84** [comment]
Glad to hear that!

If you like, also take a look at the various options. If you play on a modern TV you might want to use the 16:9 patch. The menus are going to be stretched but the game will be in real 16:9 (just remember to force it in your TV settings).

Also, you can apply other nice hacks, such as removing in-game bloom effect, dark filter, and noise effect!
